### ISSUE TITLE
Qn: about subscription

### ISSUE THREAD

**Issue by bsr203** [matiasanaya/go-graphql-subscription-example#4]
Hi @matiasanaya 

thank you for the PR to support subscription and this example. I have couple of questions

1. Can you please explain why there are two select statements inside and functions of each?
2. What is the lifetime of a subscriber? Does it terminate with a ctx.Done() call from the  framework when a websocket connection is terminated?

thanks,
bsr.
cc @pavelnikolov

**Comment by matiasanaya** [comment]
Hi @bsr203, can you please clarify question 1? Are you referring to [this](https://github.com/matiasanaya/go-graphql-subscription-example/blob/master/main.go#L126) and [this](https://github.com/matiasanaya/go-graphql-subscription-example/blob/master/main.go#L133) `select` statements?

Re: lifetime of a subscriber, the framework cancels the `context` when the web socket connection is terminated or if the client sends a `stop` command. When that happens [this](https://github.com/matiasanaya/go-graphql-subscription-example/blob/master/main.go#L134) code triggers a remove of the subscriber from the list and prevents further updates. If you are interested in how the framework works you can check out [this](https://github.com/matiasanaya/graphql-transport-ws/blob/master/graphqlws/internal/connection/connection.go) file which manages all of the websocket events.

I hope this helps :)

**Comment by bsr203** [comment]
Hi @matiasanaya 
I can't believe I forgot to link the code :-) .I mean the two select statements in [this](https://github.com/matiasanaya/go-graphql-subscription-example/blob/master/main.go#L125) go routine. Yup, you guessed it right :-)
Though I been using go a while, I haven't tried much of concurrency patterns. I wonder when the first 

```
select {
	case <-s.stop:
		unsubscribe <- id
		return
	default:
}

```
select is needed as unsubscribe is also handled in the second when `s.stop` is received!

thanks again for your help.
 Cheers

**Comment by pavelnikolov** [comment]
If/when the subscriptions PR gets merged I’d like to add some more examples.

**Comment by matiasanaya** [comment]
@bsr203 in `select` statements _If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection_. So my understanding is that in the second `select` there'd be a random choosing between "unsubscribing" and "event sending" if the context has been canceled and the events channel is free. I want to force an unsubscribe in that case and thus I've added the first `select`. This first `select` guarantees that _at most_ one event is sent to the client after the context has been canceled.

Also note that I'm no expert but I've seen this pattern elsewhere. Check [this stackoverflow answer](https://stackoverflow.com/a/46202533) for more details.

I hope this helps :)

**Comment by bsr203** [comment]
@matiasanaya Thank you for taking the time to explain the code. I will spend time on the SO answer as other answers claims the accepted one wont work. I Need to learn the fundamentals and try out. Thanks agin for your time and help. Cheers. bsr.
