### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by lindroth** [matiasanaya/go-graphql-subscription-example#6]
When I try to run the example I get:

go run main.go 
# github.com/matiasanaya/go-graphql-subscription-example/graphqlwshandler
graphqlwshandler/handler.go:54:20: h.schema.Subscribe undefined (type *graphql.Schema has no field or method Subscribe)
graphqlwshandler/handler.go:66:24: select case must be receive, send or assign recv

**Comment by matiasanaya** [comment]
Hi,

1) What version of `Go` are you running?

2) Have you ran `dep ensure` to pull down the correct dependencies for this project as per the [README.md](https://github.com/matiasanaya/go-graphql-subscription-example/blob/master/README.md)?

**Comment by lindroth** [comment]
My bad. I missed that. 
I also missed that github.com/graph-gophers/graphql-go does not support websockets yet in their main release.

**Comment by matiasanaya** [comment]
@lindroth if you are interested in this feature you can support these PR's:

* [Support graphQL subscriptions in graph-gophers/graphql-go](https://github.com/graph-gophers/graphql-go/pull/203)
* [Add a websocket transport library to graph-gophers](https://github.com/graph-gophers/graphql-transport-ws/pull/1)

**Comment by lindroth** [comment]
Already on it. I found them after starting digging. 
Do you think graph-gophers/graphql-go is good even though it is missing subscriptions or is there a more mature library that already has it? Just starting a new quite big project.

**Comment by matiasanaya** [comment]
@lindroth I would definitively use [graph-gophers/graphql-go](https://github.com/graph-gophers/graphql-go) over any other graphQL Go library. That being said, if you must have GraphQL Subscriptions (production ready) I don't think there is a good option right now and that's why I've been contributing. Hopefully that changes shortly.
